# Savaş Planı Adı
name: 'MODIE: Dövme Çekici Protokolü'

# Bu planın ne zaman çalıştırılacağını belirler
on:
  workflow_dispatch:  # Manuel olarak, bir düğmeye basarak başlatılmasını sağlar

jobs:
  launch_attack:
    # Saldırının yapılacağı sanal sunucu türü
    runs-on: ubuntu-latest

    # Bu savaşta, 100 farklı çekicin aynı anda vurmasını sağlıyoruz (paralel görevler)
    strategy:
      fail-fast: false
      matrix:
        # 1'den 100'e kadar 100 farklı sanal saldırgan oluştur
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]

    steps:
      # 1. Adım: Kodu (armor_piercer.py) sanal sunucuya indirir
      - name: Cephaneliği Konuşlandır
        uses: actions/checkout@v3

      # 2. Adım: Saldırı için Python ortamını kurar
      - name: Savaş Alanını Hazırla
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Adım: Nihai silahın mühimmatını (kütüphaneleri) kurar
      - name: Mühimmatı Yükle
        run: pip install -U curl_cffi

      # 4. Adım: Saldırıyı Başlat!
      - name: Topyekûn Savaş İlan Et
        run: python armor_piercer.py
